In [13]:
import numpy as np
import modern_robotics as mr 


xa = [0,0,1]
ya = [1,0,0]
za = np.cross(xa,ya)
za

array([0, 1, 0])

In [15]:
R_as = np.array([xa,ya,za])
R_sa = np.transpose(R_as)
print("\nQuestion 1:\n", np.array2string(R_sa, separator=',')) # question 1


Question 1:
 [[0,1,0],
 [0,0,1],
 [1,0,0]]


In [3]:
xb = [1,0,0]
yb = [0,0,-1]
zb = np.cross(xb,yb)
zb

array([0, 1, 0])

In [16]:
R_bs = np.array([xb,yb,zb])
R_sb_inverse = R_bs
print("\nQuestion 2:\n", np.array2string(R_sb_inverse, separator=',')) # question 2


Question 2:
 [[ 1, 0, 0],
 [ 0, 0,-1],
 [ 0, 1, 0]]


In [17]:
R_sb = np.transpose(R_bs)
R_sb

array([[ 1,  0,  0],
       [ 0,  0,  1],
       [ 0, -1,  0]])

In [19]:
R_ab = np.dot(R_as , R_sb) 
R_ab

array([[ 0, -1,  0],
       [ 1,  0,  0],
       [ 0,  0,  1]])

In [20]:
R_sb

array([[ 1,  0,  0],
       [ 0,  0,  1],
       [ 0, -1,  0]])

In [21]:
R_as

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [22]:
R_ab = np.array([[0,-1,0],[1,0,0],[0,0,1]]) #dot result Ras Rsb
R_ab
print("\nQuestion 3:\n", np.array2string(R_ab, separator=',')) # question 3


Question 3:
 [[ 0,-1, 0],
 [ 1, 0, 0],
 [ 0, 0, 1]]


In [23]:
P_b = np.array([[1],[2],[3]])
P_s = np.dot(R_sb,P_b) # R_sb*P_b
P_s
print("\nQuestion 5:\n", np.array2string(P_s, separator=',')) # question 5


Question 5:
 [[ 1],
 [ 3],
 [-2]]


In [24]:
w_s = np.array([[3],[2],[1]])
w_a = np.dot(R_as, w_s) # dot result (R_as * w_s) 3x3 * 3x1 = 1x3 
w_a
print("\nQuestion 7:\n", np.array2string(w_s, separator=',')) # question 7


Question 7:
 [[3],
 [2],
 [1]]


In [25]:
R_sa.shape

(3, 3)

In [27]:
#matrixlog
matrixlog = mr.MatrixLog3(R_sa)
matrixlog

array([[ 0.        ,  1.20919958, -1.20919958],
       [-1.20919958,  0.        ,  1.20919958],
       [ 1.20919958, -1.20919958,  0.        ]])

In [30]:
# convert so3 to vector
vector8 = mr.so3ToVec(matrixlog) 
vector8

array([-1.20919958, -1.20919958, -1.20919958])

In [36]:
#tetha_of_matrixlog
tetha_of_matrixlog = mr.AxisAng3(vector8)
tetha_of_matrixlog = tetha_of_matrixlog[1]
tetha_of_matrixlog
# quiz answer 2.094

2.0943951023931957

In [145]:
#vec to so3
omega_hat_tetha= np.array([[1],[2],[0]])
so3 = mr.VecToso3(omega_hat_tetha)

#matexp
so3_1 = np.array([[0,0,2],[0,0,-1],[-2,1,0]])
matexp = mr.MatrixExp3(so3_1)

In [146]:
so3

array([[0, array([0]), array([2])],
       [array([0]), 0, array([-1])],
       [array([-2]), array([1]), 0]], dtype=object)

In [147]:
so3_1

array([[ 0,  0,  2],
       [ 0,  0, -1],
       [-2,  1,  0]])

In [148]:
matexp

array([[-0.2938183 ,  0.64690915,  0.70368982],
       [ 0.64690915,  0.67654542, -0.35184491],
       [-0.70368982,  0.35184491, -0.61727288]])

In [138]:
omega_hat_tetha_10 = np.array([[1],[2],[0.5]])
so3_10 = mr.VecToso3(omega_hat_tetha_10)
so3_10_1 = np.array([[0,-0.5,2],[0.5,0,-1],[-2,1,0]])

In [134]:
so3_10

array([[0, array([-0.5]), array([2.])],
       [array([0.5]), 0, array([-1.])],
       [array([-2.]), array([1.]), 0]], dtype=object)

In [139]:
so3_10_1

array([[ 0. , -0.5,  2. ],
       [ 0.5,  0. , -1. ],
       [-2. ,  1. ,  0. ]])

In [142]:
so3_11 = np.array([[0,0.5,-1],[-0.5,0,2],[1,-2,0]])
matrixexp = mr.MatrixExp3(so3_11)

In [143]:
matrixexp

array([[ 0.60482045,  0.796274  , -0.01182979],
       [ 0.46830057, -0.34361048,  0.81401868],
       [ 0.64411707, -0.49787504, -0.58071821]])

In [144]:
R_12 = np.array([[0,0,1],[-1,0,0],[0,-1,0]])
matrixlog_12 = mr.MatrixLog3(R_12)
matrixlog_12

array([[ 0.        ,  1.20919958,  1.20919958],
       [-1.20919958,  0.        ,  1.20919958],
       [-1.20919958, -1.20919958,  0.        ]])