In [58]:
import math
import numpy as np
from numpy import linalg as LA
import modern_robotics as mr

pi = np.pi

#q1
f_1 = np.array([[0],[0],[0],[2],[0],[0]])
s1_1 = np.array([[0],[0],[1],[0],[0],[0]])
s2_1 = np.array([[0],[0],[1],[0],[-1],[0]])
s3_1 = np.array([[0],[0],[1],[0],[-2],[0]])
S_1 = np.c_[s1_1,s2_1,s3_1] 
tetha_1 = np.array([0,pi/4,0]) 
Js_1 = mr.JacobianSpace(S_1,tetha_1)
tau_1 = np.dot(Js_1.T,f_1)
tau_rounded_1 = np.around(tau_1, decimals=2)
tau_rounded_1

array([[0.  ],
       [0.  ],
       [1.41]])

In [50]:
#q2
#variables

tetha_2 = np.array([0,0,pi/2,-pi/2])
f_2 = np.array([0,0,10,10,10,0])
b1_2 = np.array([[0],[0],[1],[0],[4],[0]])
b2_2 = np.array([[0],[0],[1],[0],[3],[0]])
b3_2 = np.array([[0],[0],[1],[0],[2],[0]])
b4_2 = np.array([[0],[0],[1],[0],[1],[0]])
B_2 = np.c_[b1_2,b2_2,b3_2,b4_2]

Jb_2 = mr.JacobianBody(B_2, tetha_2)
tau_2 = np.dot(Jb_2.T,f_2)
tau_rounded_2 = np.around(tau_2, decimals=2)
tau_rounded_2

array([30., 20., 10., 20.])

In [62]:
#q3
s1_3 = np.array([[0],[0],[1],[0],[0],[0]]) 
s2_3 = np.array([[1],[0],[0],[0],[2],[0]])
s3_3 = np.array([[0],[0],[0],[0],[1],[0]])
S_3 = np.c_[s1_3,s2_3,s3_3]
tetha_3 = np.array([pi/2,pi/2,1])
Js_3 = mr.JacobianSpace(S_3,tetha_3)
Js_rounded_3 = np.around(Js_3, decimals=3)
Js_rounded_3

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0., -2., -0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [63]:
#q4
b1_4 = np.array([[0],[1],[0],[3],[0],[0]]) 
b2_4 = np.array([[-1],[0],[0],[0],[3],[0]])
b3_4 = np.array([[0],[0],[0],[0],[0],[1]])
B_4 = np.c_[b1_4,b2_4,b3_4]
tetha_4 = np.array([pi/2,pi/2,1])
Jb_4= mr.JacobianBody(B_4,tetha_4)
Jb_rounded_4 = np.around(Jb_4, decimals=2)
Jb_rounded_4


array([[ 0., -1.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  1.]])

In [29]:
#q5
#7R WAM robot
tetha_5 = np.array([pi/2,pi/2,pi/2,pi/2,pi/2,pi/2,pi/2])
Jb_5 = np.array([[ 0     ,-1     , 0     , 0     ,-1     , 0     , 0],
                 [ 0     , 0     , 1     , 0     , 0     , 1     , 0],
                 [ 1     , 0     , 0     , 1     , 0     , 0     , 1],
                 [-0.105 , 0     , 0.006 ,-0.045 , 0     , 0.006 , 0],
                 [-0.889 , 0.006 , 0     ,-0.844 , 0.006 , 0     , 0],
                 [ 0     ,-0.105 , 0.889 , 0     , 0     , 0     , 0]])
                 
Jv_5 = Jb_5[3:]
A_5 = np.dot(Jv_5,Jv_5.T)
eigenvalue_5, eigenvector_5 = LA.eig(A_5)
maximum_index = np.where(eigenvalue_5 == np.amax(eigenvalue_5))[0][0]

# the directions of the longest principal semi-axes of the ellipsoid
max_direction_5 = eigenvector_5[maximum_index]
max_direction_5_rounded = np.around(max_direction_5, decimals=3)

# the length of the longest principal semi axes of the ellipsoid
max_length_5 = math.sqrt(eigenvalue_5[maximum_index])
max_length_5_rounded = np.around(max_length_5, decimals=3)


In [31]:
max_direction_5_rounded

array([ 0.087,  0.996, -0.   ])

In [9]:
# question 5
Jb_5 = np.array([[ 0.   ,  0.   ,  1.   , -0.105, -0.889,  0.   ],
                 [-1.   ,  0.   ,  0.   ,  0.   ,  0.006, -0.105],
                 [ 0.   ,  1.   ,  0.   ,  0.006,  0.   ,  0.889],
                 [ 0.   ,  0.   ,  1.   , -0.045, -0.844,  0.   ],
                 [-1.   ,  0.   ,  0.   ,  0.   ,  0.006,  0.   ],
                 [ 0.   ,  1.   ,  0.   ,  0.006,  0.   ,  0.   ],
                 [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ]]).T
Jv_5 = Jb_5[3:]

A_5 = np.dot(Jv_5, Jv_5.T)
w_5, v_5 = LA.eig(A_5)
maxId_5 = np.where(w_5 == np.amax(w_5))[0][0]

vecPAxis = v_5[maxId_5]
vecPAxis_off = np.around(vecPAxis, decimals=2)
print("\nQuestion 5:\n", np.array2string(vecPAxis_off, separator=','))

# question 6
lenPAxis = math.sqrt(w_5[maxId_5])
lenPAxis_off = np.around(lenPAxis, decimals=2)
print("\nQuestion 6:\n", np.array2string(lenPAxis_off, separator=','))


Question 5:
 [ 0.09, 1.  ,-0.  ]

Question 6:
 1.23


In [27]:
np.amax(w_5)

1.5142181453597041