In [77]:
import numpy as np
import modern_robotics as mr 

xa1 = [0,0,1]
ya1 = [-1,0,0]
za1 = np.cross(xa1,ya1)
R_as1 = np.array([xa1,ya1,za1])
R_as1

array([[ 0,  0,  1],
       [-1,  0,  0],
       [ 0, -1,  0]])

In [78]:
R_sa1 = R_as1.T
np.shape(R_sa1)

(3, 3)

In [103]:
last_row = np.array([np.zeros((3,), dtype=int)])
np.shape(last_row)
R_sa1_r = np.vstack([R_sa1,last_row])
R_sa1_r.shape

(4, 3)

In [107]:
p_a1 = np.array([[0,0,1]])
p_a1 = np.array([np.append(p_a1,[1])])
p_a1 = p_a1.T
p_a1.shape

(4, 1)

In [121]:
#q1
T_sa1 = np.append(R_sa1_r , p_a1,1) 
T_sa1
# T = ([R,p],[0,1])  

array([[ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 1,  0,  0,  1],
       [ 0,  0,  0,  1]])

In [109]:
xb2 = [1,0,0]
yb2 = [0,0,-1]
zb2 = np.cross(xb2,yb2)
R_bs2 = np.array([xb2,yb2,zb2])
R_bs2

array([[ 1,  0,  0],
       [ 0,  0, -1],
       [ 0,  1,  0]])

In [110]:
R_sb2 = R_bs2.T
R_sb2

array([[ 1,  0,  0],
       [ 0,  0,  1],
       [ 0, -1,  0]])

In [111]:
R_sb2_r = np.vstack([R_sb2,last_row])
R_sb2_r.shape

(4, 3)

In [112]:
p_b2 = np.array([[0,2,0]])
p_b2 = np.array([np.append(p_b2,[1])])
p_b2 = p_b2.T
p_b2.shape

(4, 1)

In [148]:
#q2
T_sb2 = np.append(R_sb2_r , p_b2,1) 
T_bs2 = mr.TransInv(T_sb2)
T_sb2

array([[ 1,  0,  0,  0],
       [ 0,  0,  1,  2],
       [ 0, -1,  0,  0],
       [ 0,  0,  0,  1]])

In [185]:
T_bs2

array([[ 1,  0,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  1,  0, -2],
       [ 0,  0,  0,  1]])

In [122]:
#q3
T_as1 = mr.TransInv(T_sa1)
T_ab3 = np.dot(T_as1,T_sb2)
T_ab3

array([[ 0, -1,  0, -1],
       [-1,  0,  0,  0],
       [ 0,  0, -1, -2],
       [ 0,  0,  0,  1]])

In [125]:
#q5
p_b5 = [1,2,3]
p_b5 = np.array([np.append(p_b5,1)])
p_b5 = p_b5.T
p_s5 = np.dot(T_sb2,p_b5)
p_s5 = np.delete(p_s5,3)
p_s5

array([ 1,  5, -2])

In [130]:
#q7
v_s7 = np.array([[3],[2],[1],[-1],[-2],[-3]])
T_as1_adj = mr.Adjoint(T_as1)
v_a7 = np.dot(T_as1_adj,v_s7,)
v_a7

array([[ 1.],
       [-3.],
       [-2.],
       [-3.],
       [-1.],
       [ 5.]])

In [140]:
#q8
matrixlog_8 =mr.MatrixLog6(T_sa1)
print("matrixlog\n")
print(matrixlog_8,"\n")
vector_8 = mr.se3ToVec(matrixlog_8) 
print("vector\n")
print(vector_8,"\n")
tetha_of_matrixlog_8 = mr.AxisAng6(vector_8)
tetha_of_matrixlog_8 = tetha_of_matrixlog_8[1] 
print("tetha\n",tetha_of_matrixlog_8)

matrixlog

[[ 0.         -1.20919958 -1.20919958  0.73639986]
 [ 1.20919958  0.         -1.20919958  0.47279972]
 [ 1.20919958  1.20919958  0.          0.73639986]
 [ 0.          0.          0.          0.        ]] 

vector

[ 1.20919958 -1.20919958  1.20919958  0.73639986  0.47279972  0.73639986] 

tetha
 2.0943951023931957


In [141]:
#q9
# vector to se3
vector_9 = np.array([0,1,2,3,0,0])
se3_9 =  mr.VecTose3(vector_9)
print("matrix se3\n", se3_9)
# matrix exp
matrixexp_9 = mr.MatrixExp6(se3_9)
print("matrix exp\n", matrixexp_9)

matrix se3
 [[ 0. -2.  1.  3.]
 [ 2.  0.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
matrix exp
 [[-0.61727288 -0.70368982  0.35184491  1.05553472]
 [ 0.70368982 -0.2938183   0.64690915  1.94072745]
 [-0.35184491  0.64690915  0.67654542 -0.97036373]
 [ 0.          0.          0.          1.        ]]


In [194]:
#q10
#force in b to force in s
fb_10 = np.array([[1,0,0,2,1,0]])
fb_10 = fb_10.T
print ("fb\n",fb_10)
#convert Tsb to adj Tsb
adj_T_bs2 = mr.Adjoint(T_bs2)
print ("Adj of T_sb2\n",adj_T_bs2)
adj_T_bs2_transpose = np.transpose(adj_T_bs2)
# dot product fb*adj_Tbs to find fs
fs_10 = np.dot(adj_T_bs2_transpose,fb_10)
print("fs\n",fs_10)

fb
 [[1]
 [0]
 [0]
 [2]
 [1]
 [0]]
Adj of T_sb2
 [[ 1.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0. -2.  1.  0.  0.]
 [-2.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  1.  0.]]
fs
 [[-1.]
 [ 0.]
 [-4.]
 [ 2.]
 [ 0.]
 [-1.]]


In [165]:
#q11
T_11 = np.array([[0,-1,0,3],[1,0,0,0],[0,0,1,1],[0,0,0,1]])
print("T\n",T_11,"\n")
T_inv_11 = mr.TransInv(T_11)
print("T inverse\n",T_inv_11,"\n")

T
 [[ 0 -1  0  3]
 [ 1  0  0  0]
 [ 0  0  1  1]
 [ 0  0  0  1]] 

T inverse
 [[ 0  1  0  0]
 [-1  0  0  3]
 [ 0  0  1 -1]
 [ 0  0  0  1]] 



In [172]:
#q12
v_12 = np.array([[1,0,0,0,2,3]])
v_12 = v_12.T
print("v\n",v_12,"\n")
se3_12 = mr.VecTose3(v_12)
print("matrix se3 \n", se3_12)


v
 [[1]
 [0]
 [0]
 [0]
 [2]
 [3]] 

matrix se3 
 [[0 array([0]) array([0]) 0]
 [array([0]) 0 array([-1]) 2]
 [array([0]) array([1]) 0 3]
 [0.0 0.0 0.0 0.0]]


In [177]:
#q13
screw_13 = np.array([1,0,0]) # direction unit vector
p_13 = np.array([0,0,2]) # point
h = 1 #pitch
screw_normalized_13 = mr.ScrewToAxis(p_13,screw_13,h)
print("S \n", screw_normalized_13)

S 
 [1 0 0 1 2 0]


In [182]:
#q14
se3_14 = np.array([[0,-1.5708,0,2.3562],[1.5708,0,0,-2.3562],[0,0,0,1],[0,0,0,0]])
print("se3 \n",se3_14,"\n")
matrixexp_14 = mr.MatrixExp6(se3_14)
print("Matrix EXP T (SE3)\n", matrixexp_14)

se3 
 [[ 0.     -1.5708  0.      2.3562]
 [ 1.5708  0.      0.     -2.3562]
 [ 0.      0.      0.      1.    ]
 [ 0.      0.      0.      0.    ]] 

Matrix EXP (SE3)
 [[-3.67320510e-06 -1.00000000e+00  0.00000000e+00  3.00000551e+00]
 [ 1.00000000e+00 -3.67320510e-06  0.00000000e+00  5.50981777e-06]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [183]:
#q15
T_15 = np.array([[0,-1,0,3],[1,0,0,0],[0,0,1,1],[0,0,0,1]])
print("T \n",T_15,"\n")
se3_15 = mr.MatrixLog6(T_15)
print("se3 \n",se3_15)

T 
 [[ 0 -1  0  3]
 [ 1  0  0  0]
 [ 0  0  1  1]
 [ 0  0  0  1]] 

se3 
 [[ 0.         -1.57079633  0.          2.35619449]
 [ 1.57079633  0.          0.         -2.35619449]
 [ 0.          0.          0.          1.        ]
 [ 0.          0.          0.          0.        ]]


In [117]:
T_sb = np.array([[1, 0, 0, 0],
                 [0, 0, 1, 2],
                 [0,-1, 0, 0],
                 [0, 0, 0, 1]])

T_bs = mr.TransInv(T_sb)
print("\nQuestion 2:\n", np.array2string(T_bs, separator=',')) # question 2


Question 2:
 [[ 1, 0, 0, 0],
 [ 0, 0,-1, 0],
 [ 0, 1, 0,-2],
 [ 0, 0, 0, 1]]
